[[redirects]]
from = "/api/*"
to = "https://apis.data.go.kr/B552584/:splat"
status = 200
force = true

[[redirects]]
from = "/weather/*"
to = "https://api.openweathermap.org/:splat"
status = 200
force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200